version: '3'

services:
  oauth2-proxy:
    container_name: oauth2-proxy
    hostname: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    environment:
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_COOKIE_SECRET: "UPYzWX20HgyqBuvoWyxWwNbMsAL8Go8D"
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_OIDC_ISSUER_URL: https://vwautocloud--accenture3.sandbox.my.salesforce.com
      OAUTH2_PROXY_COOKIE_DOMAINS: https://accenturenikhil-upgraded-space-guacamole-g9p9wx4g4vgc9rrw-7007.preview.app.github.dev
      OAUTH2_PROXY_UPSTREAMS: file:///dev/null
      OAUTH2_PROXY_WHITELIST_DOMAINS: vwautocloud--accenture3.sandbox.my.salesforce.com,accenturenikhil-upgraded-space-guacamole-g9p9wx4g4vgc9rrw-7007.preview.app.github.dev
      OAUTH2_PROXY_CLIENT_SECRET: 731616EAA7B9F8F3C877B9F5CA242C36599BFAB1B42504806EBFB25CFC53D335
      OAUTH2_PROXY_CLIENT_ID: 3MVG99H7o8BRmFkUk045hHu2.xwnYWm3gVGnkAxV9X3tTpxo2qKl9rwAzaI5ZHRnkuz4m6.5wnX5PmLAeb.pH
      OAUTH2_PROXY_REDIRECT_URL: https://accenturenikhil-upgraded-space-guacamole-g9p9wx4g4vgc9rrw-3000.preview.app.github.dev/oauth2/callback
      OAUTH2_PROXY_PROVIDER: oidc
      OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS: "true" 
      OAUTH2_PROXY_JWT_KEY_FILE: /workspaces/backstage/jwt_signing_key.pem
    restart: unless-stopped
    network_mode: "host"